name: tests

on: [push]

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install composer dependencies
      run: composer install --prefer-dist

    - name: Install npm dependencies
      run: npm install

    - name: Generate encryption key
      run: php artisan key:generate

    - name: Build assets
      run: npm run production

    - name: Run test suite
      run: php8.0 vendor/bin/phpunit
